version: 1.0.{build}-{branch}
# branches to build
branches:
  # whitelist
  only:
    - master
    - production

  # blacklist
  except:
    - gh-pages
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

install:
  - cinst miniconda3
  - refreshenv
  - set PATH=%PATH%;C:\Tools\miniconda3;C:\Tools\miniconda3\Scripts
  - activate root
  - python setup.py test


