version: 1.0.{build}-{branch}
# branches to build
branches:
  # whitelist
  only:
    - master
    - production

  # blacklist
  except:
    - gh-pages
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

install:
  - 'choco install miniconda3 --ia="/AddToPath:1"'
  - refreshenv
  - where python
  - where conda
